# Project: LISS
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../oct302024/main.o
LINKOBJ  = ../oct302024/main.o
LIBS     = -L"F:/Programas/Windows/Portables/Apps/DevC/Dev-Cpp/TDM-GCC-64/lib" -L"F:/Programas/Windows/Portables/Apps/DevC/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"F:/Programas/Windows/Portables/Apps/DevC/Dev-Cpp/TDM-GCC-64/include" -I"F:/Programas/Windows/Portables/Apps/DevC/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"F:/Programas/Windows/Portables/Apps/DevC/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"F:/Programas/Windows/Portables/Apps/DevC/Dev-Cpp/TDM-GCC-64/include" -I"F:/Programas/Windows/Portables/Apps/DevC/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"F:/Programas/Windows/Portables/Apps/DevC/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"F:/Programas/Windows/Portables/Apps/DevC/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = LISS.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = F:\Programas\Windows\Portables\Apps\DevC\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../oct302024/main.o: ../oct302024/main.c
	$(CC) -c ../oct302024/main.c -o ../oct302024/main.o $(CFLAGS)
